version: "3.5"

services:
  local_db:
    container_name: trello_db_container
    image: postgres
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "1"
      PGDATA: /data/postgres
    volumes:
      - /Users/maksimparkhomenka/Documents/work/bull.js/docker:/data/postgres
    ports:
      - "2222:5432"
    restart: unless-stopped

  local_admin:
    container_name: trello_db_admin_container
    image: dpage/pgadmin4:4.21
    environment:
      PGADMIN_DEFAULT_EMAIL: "trello@pgadmin.org"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
      - ./tmp/storages/trello_pgadmin:/root/.pgadmin
    ports:
      - "1111:80"
    restart: unless-stopped
    depends_on:
      - local_db