version: "3.5"
services:
  bot_redis:
    image: "bitnami/redis:latest"
    container_name: "bot_redis_container"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - ${REDIS_QUEUE_PORT}:6379
    restart: unless-stopped
    command: redis-server --requirepass 1
